In [1]:
import pandas as pd
import numpy as np

In [2]:
# Pre and Post Session Surveys from AY18-19 (year1) and AY19-20 (year2)

year1_pre = pd.read_excel("Pre and post tests AY18–19/TaraProject_AY18–19Student Pre-Session Survey_ Academic Coaching  (Responses).xlsx")
year1_post = pd.read_excel("Pre and post tests AY18–19/TaraProject_AY18–19Student Post-Session Survey_ Academic Coaching  (Responses).xlsx")
year2_pre = pd.read_excel("Pre and post tests AY19–20/TaraProject_AY19–20Academic Coaching_ Pre-Session Student Survey  (Responses).xlsx")
year2_post = pd.read_excel("Pre and post tests AY19–20/TaraProject_AY19–20Academic Coaching_ Post-Session Student Survey  (Responses).xlsx")
pre_post = {"Pre1": year1_pre, "Post1": year1_post, "Pre2": year2_pre, "Post2": year2_post}

# Initial Consultations
initial_raw = pd.read_excel("TaraProject_AY19–20Initial Consultation (Intake) Form - AY 19-20 (Responses).xlsx")

# AC Roster Information
ac_roster = pd.read_excel("TaraProject_AY19–20AC Roster AY 19-20.xlsx", sheet_name = None)

In [17]:
# Combine AC Rosters from both years

ac_roster1 = ac_roster['18-19 Photo Roster'].drop(columns=['Unnamed: 0', 'PHONE'])
ac_roster2 = ac_roster['19-20 roster'].drop(columns=['Unnamed: 14', 'AY 19-20 Wage', 'Phone Number',
                                                    'Expected Grad'])
ac_roster1 = ac_roster1.rename(columns = {'LAST NAME' : 'Last Name', 'PREFERRED NAME': 'Pref Name', 'First name': 
                                          'First Name','Class Level':'Class Rank'})

college = []
for i in range(len(ac_roster1['Major'])):
    L = ac_roster1['Major'][i].split('-')
    if(len(L) == 2):
        college += [L[0].strip().upper()]
        ac_roster1['Major'][i] = L[1].strip()
    else:
        college += ['NA']
ac_roster1['College'] = college
ac_roster1['Year'] = '18-19'
ac_roster2['Year'] = '19-20'
ac_roster_full = pd.merge(ac_roster1, ac_roster2, how='outer', on=['AndrewID', 'Last Name', 'First Name', 'Pref Name',
                                                 'Year', 'Major', 'College', 'Class Rank'], copy=False)
name = []
for i in range(len(ac_roster_full)):
    name += [ac_roster_full['First Name'][i] + ' ' + ac_roster_full['Last Name'][i]]
ac_roster_full['Full Name'] = name
ac_roster_full = ac_roster_full.drop(columns=['Last Name'])
ac_roster_full = ac_roster_full.append({'First Name': 'Michael', 'AndrewID':'mpoljak', 'Full Name': 'Michael Poljak',
                                       'Pref Name': 'Mike'},
                                      ignore_index=True)
ac_roster_full = ac_roster_full.append({'First Name': 'TC', 'AndrewID':'tce', 'Full Name': 'TC Eley'},
                                      ignore_index=True)
ac_roster_full

,Pref Name,First Name,AndrewID,Major,Class Rank,College,Year,Gender,Language(s),Countries,Other,Full Name
0,Aden,Aden,ahalpern,Int. Rel /Beh. Eco,Sophomore,DC,18-19,NaN,NaN,NaN,NaN,Aden Halpern
1,Andrew,Andrew,siheonl,IS,Junior,DC,18-19,NaN,NaN,NaN,NaN,Andrew Lee
2,Ani,Anirudh,anirudhr,ECE,Graduate,CIT,18-19,NaN,NaN,NaN,NaN,Anirudh Ramakrishnan
3,Boyao,Boyao,boyaoy,MechE,Senior,CIT,18-19,NaN,NaN,NaN,NaN,Boyao Yu
4,Caroline,Caroline,cmadigan,Bio/History,Junior,SHS,18-19,NaN,NaN,NaN,NaN,Caroline Madigan
5,Clare,Clare,cxlai,CS,Senior,SCS,18-19,NaN,NaN,NaN,NaN,Clare Lai
6,Dylan,Dylan,Dgreynol,Biomed/MechE,Sophomore,CIT,18-19,NaN,NaN,NaN,NaN,Dylan Greynolds
7,Emily,Emily,ebippus,Pub. Policy,Graduate,HC,18-19,NaN,NaN,NaN,NaN,Emily Bippus
8,Hamza,Hamza,hqq,ARC,NaN,CFA,18-19,NaN,NaN,NaN,NaN,Hamza Qureshi
9,Josh,Josh,jlefevre,Des. Interaction,Graduate,CFA,18-19,NaN,NaN,NaN,NaN,Josh LeFevre
10,Julia,Julia,jkoltas,Math,Senior,MCS,18-19,NaN,NaN,NaN,NaN,Julia Koltas
11,Julian,Julian,jtrulear,ECE,Graduate,CIT,18-19,NaN,NaN,NaN,NaN,Julian Trulear
12,Lethe,Yuchi,yuchiz,ECE,Sophomore,CIT,18-19,NaN,NaN,NaN,NaN,Yuchi Zhang
13,Max,Max,mfarfel,MSE,Senior,CIT,18-19,NaN,NaN,NaN,NaN,Max Farfel
14,Meera,Meera,meeramak,Bio/Neuro,Sophomore,SHS,18-19,NaN,NaN,NaN,NaN,Meera Krishna
15,Michael,Michael,myou,ECE,Junior,CIT,18-19,NaN,NaN,NaN,NaN,Michael You
16,Miguel,Miguel,mtwahirw,ISM,Graduate,HC,18-19,NaN,NaN,NaN,NaN,Miguel Twahirwa
17,Mikaela,Mikaela,mblewis,Bio,Graduate,MCS,18-19,NaN,NaN,NaN,NaN,Mikaela Lewis
18,Namita,Namita,namitat,Neurosci,Junior,MCS,18-19,NaN,NaN,NaN,NaN,Namita Thomas
19,Nandini,Nandini,nradhakr,Bus. Admin,Senior,TBS,18-19,NaN,NaN,NaN,NaN,Nandini Radhakrishnan
20,Noah,Noah,noahl,Comp. Bio,Junior,MCS,18-19,NaN,NaN,NaN,NaN,Noah Lee
21,Orchi,Orchi,obanerje,Dec. Sci.,NaN,SHS,18-19,NaN,NaN,NaN,NaN,Orchi Banerjee
22,Prerana,Prerana,pkatiyar,Neurosci,Senior,MCS,18-19,NaN,NaN,NaN,NaN,Prerana Katiyar
23,Roman,Roman,rkaufman,IS,NaN,DC,18-19,NaN,NaN,NaN,NaN,Roman Kaufman
24,Roosha,Roosha,rmandal,Comp. Bio,NaN,SHS,18-19,NaN,NaN,NaN,NaN,Roosha Mandal
25,Sarah,Sarah,sklotz,Bio/French,Junior,MCS,18-19,NaN,NaN,NaN,NaN,Sarah Klotz
26,Tara,Tara,tjawahar,Stats/ML,Junior,DC,18-19,NaN,NaN,NaN,NaN,Tara Jawahar
27,NaN,Aden,ahalpern,Int. Rel. + Behavioral Econ,Junior,DC,19-20,M,NaN,NaN,I speak proficient spanish/portuguese (but not...,Aden Halpern
28,Gus,Augustus,asaalfel,IS + Creative Writing,Sophomore,DC,19-20,M,French,Switzerland + Senegal,NaN,Augustus Saalfeld
29,NaN,Boyao,boyaoy,Mech+BioE,Graduate,CIT,19-20,M,Chinese,China,NaN,Boyao Yu
30,NaN,Caroline,cmadigan,Bio + history (min),Senior,SHS,19-20,F,NaN,NaN,NaN,Caroline Madigan
31,Coco,Courtney,callred,Art (min) HCI,Senior,CFA,19-20,F,NaN,NaN,I have learning disabilities and the skills co...,Courtney Allred
32,NaN,David,ddonehue,Bio Sci,Sophomore,MCS,19-20,M,NaN,NaN,Grew up single parent household. Grew up livin...,David Donehue
33,NaN,Dylan,dgreynol,MechE + Biomedical,Junior,CIT,19-20,M,NaN,NaN,NaN,Dylan Greynolds
34,NaN,Ella,eirosenb,Drama (min) innov & entre,Junior,CFA,19-20,F,Hungarian,Hawaii + USA,NaN,Ella Rosenblum
35,NaN,Iana,idobreva,Drama,Sophomore,CFA,19-20,F,NaN,Bulgaria,NaN,Iana Dobreva
36,Clara,Jieli,jieliz1,Architecture (min) music,Junior,CFA,19-20,F,Chinese,China,NaN,Jieli Zhao
37,NaN,Katie,katielee,Chem/Bio Chem Track,Sophomore,MCS,19-20,F,NaN,NaN,NaN,Katie Lee
38,Cristina,Maria,mpullen,Pro Writ.,Junior,DC,19-20,F,NaN,NaN,NaN,Maria Pullen
39,NaN,Max,mfarfel,Mat Sci Eng (G+U),Graduate,CIT,19-20,M,NaN,NaN,NaN,Max Farfel
40,NaN,Meera,meeramak,"Neurobiology, Creative Writing",Junior,SHS,19-20,F,"Hindi, Malayalam, Kannada",India,LGBTQ+,Meera Krishna
41,NaN,Melinda,mlooney,Arc & Build Sci/Tech,Sophomore,CFA,19-20,F,NaN,NaN,NaN,Melinda Looney
42,NaN,Michael,myou,ECE + CS,Graduate,CIT,19-20,M,Chinese,NaN,NaN,Michael You
43,NaN,Nandini,nradhakr,Pub Policy/Mgt + business/stats (U),Graduate,HC/TSB,19-20,F,"Malayalam, some Hindi",India,NaN,Nandini Radhakrishnan
44,NaN,Noah,noahl,Comp Bio (min) Design for Learning,Senior,SCS,19-20,M,NaN,NaN,NaN,Noah Lee
45,NaN,Sanjana,sjobalia,Undeclared DC,Sophomore,DC,19-20,F,NaN,NaN,NaN,Sanjana Jobalia
46,NaN,Sarah,sklotz,Bio + French,Senior,MCS,19-20,F,French,NaN,Experience with overcoming mental health issues,Sarah Klotz
47,NaN,Serena,sgillian,Policy & Mgt,Senior,DC,19-20,F,NaN,USA,NaN,Serena Gillian
48,Andrew,Siheon,siheonl,IS + HCI,Senior,DC,19-20,M,Korean,Korea,NaN,Siheon Lee
49,NaN,Tara,tjawahar,Stats & ML + (min) CS and biomed eng,Senior,DC,19-20,F,NaN,USA,NaN,Tara Jawahar
50,Themi,Themistokles,tbournia,Cognitive science,Sophomore,DC,19-20,M,NaN,NaN,NaN,Themistokles Bournias
51,Adam,Xiaotian,xiaotiah,Architecture,Junior,CFA,19-20,M,Japanese,"Japan, China",NaN,Xiaotian He
52,Ying,Yingxue,yingxueh,IS,Sophomore,DC,19-20,F,NaN,NaN,NaN,Yingxue Hu
53,Steve,Young Do,youngdok,Stats & ML,Senior,DC,19-20,M,Korean,Korea,NaN,Young Do Kim
54,Lethe,Yuchi,yuchiz,ECE+Comp Fin (min) CS,Junior,CIT,19-20,F,Chinese,China,NaN,Yuchi Zhang
55,John,Ziyi,ziyix,Mat Sci Eng (min) electronic mat,Junior,CIT,19-20,M,Chinese,China,NaN,Ziyi Xu
56,Mike,Michael,mpoljak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Michael Poljak
57,NaN,TC,tce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TC Eley

In [18]:
# Change column names and drop columns that are irrelevant to data analysis

questions1, questions2 = [], []
for col in range(6,59):
    questions1 += [pre_post['Pre1'].columns[col]]
    pre_post['Pre1'] = pre_post['Pre1'].rename(columns={pre_post['Pre1'].columns[col] : col-5})
    pre_post['Post1'] = pre_post['Post1'].rename(columns={pre_post['Post1'].columns[col+1] : col-5})
for col in range(7,55):
    questions2 += [pre_post['Pre2'].columns[col]]
    pre_post['Pre2'] = pre_post['Pre2'].rename(columns={pre_post['Pre2'].columns[col] : col-6})
    pre_post['Post2'] = pre_post['Post2'].rename(columns={pre_post['Post2'].columns[col+1] : col-6})

# Pre 1:
pre_post['Pre1'] = pre_post['Pre1'].drop(columns = pre_post['Pre1'].columns[1:4])
pre_post['Pre1'] = pre_post['Pre1'].drop(columns = pre_post['Pre1'].columns[-5:])
pre_post['Pre1'] = pre_post['Pre1'].rename(columns={pre_post['Pre1'].columns[1] : 'AndrewID', 
                                              pre_post['Pre1'].columns[2] : 'Goals'})

# Pre 2:
pre_post['Pre2'] = pre_post['Pre2'].drop(columns = pre_post['Pre2'].columns[1:5])
pre_post['Pre2'] = pre_post['Pre2'].rename(columns={pre_post['Pre2'].columns[1] : 'AndrewID', 
                                              pre_post['Pre2'].columns[2] : 'Goals'})

# Post 1:
pre_post['Post1'] = pre_post['Post1'].drop(columns = pre_post['Post1'].columns[-12:])
pre_post['Post1'] = pre_post['Post1'].drop(columns = pre_post['Post1'].columns[1:5])
pre_post['Post1'] = pre_post['Post1'].rename(columns={pre_post['Post1'].columns[1] : 'AndrewID', 
                                              pre_post['Pre2'].columns[2] : 'Goals'})

# Post 2:
pre_post['Post2'] = pre_post['Post2'].drop(columns = pre_post['Post2'].columns[1:6])
pre_post['Post2'] = pre_post['Post2'].rename(columns={pre_post['Post2'].columns[1] : 'AndrewID'})

In [19]:
pre_post['Post1'].iloc[43,1] = 'sallya'
pre_post['Post1'] = pre_post['Post1'].drop(index=32)

In [20]:
# Identify students who have both pre-test and post-test data
students1 = pd.merge(pre_post['Pre1'], pre_post['Post1'], how='inner', on='AndrewID')['AndrewID'].drop_duplicates()
students2 = pd.merge(pre_post['Pre2'], pre_post['Post2'], how='inner', on='AndrewID')['AndrewID'].drop_duplicates()
students_complete = pd.merge(students1, students2, how='outer')

In [21]:
print(len(pre_post['Pre1']), len(pre_post['Post1']), len(pre_post['Pre2']), len(pre_post['Post2']))
print(len(students1), len(students2), len(students_complete))

209 109 254 86
63 68 131

In [22]:
# Drop students who do not have both pre-test and post-test data available
pre_post['Pre1'] = pd.merge(pre_post['Pre1'], students_complete, on='AndrewID')
pre_post['Post1'] = pd.merge(pre_post['Post1'], students_complete, on='AndrewID')
pre_post['Pre2'] = pd.merge(pre_post['Pre2'], students_complete, on='AndrewID')
pre_post['Post2'] = pd.merge(pre_post['Post2'], students_complete, on='AndrewID')
print(len(pre_post['Pre1']), len(pre_post['Post1']), len(pre_post['Pre2']), len(pre_post['Post2']))

73 72 73 75

In [61]:
# Split dataset into subjective measures of student, subjective measures of AC/feedback, goals, and demographics

demographics = pd.concat([pre_post['Pre1'].iloc[:,[0,1,56,57,58,59,60]],
                pre_post['Pre2'].iloc[:,[0,1,53,54,55,56,57,58,59]]])
goals_pre = pd.concat([pre_post['Pre1'].iloc[:,0:3], pre_post['Pre2'].iloc[:,0:3]])
goals_post = pd.concat([pre_post['Post1'].iloc[:,0:3], pre_post['Post2'].iloc[:,0:3]])

subjective_measures_of_self = {'Pre': pd.concat([pd.concat([pre_post['Pre1'].iloc[:,[0,1]], pre_post['Pre1'].iloc[:,3:56]], axis=1),
                                               pd.concat([pre_post['Pre2'].iloc[:,[0,1]], pre_post['Pre2'].iloc[:,3:51]], axis=1)]),
                               'Post': pd.concat([pd.concat([pre_post['Post1'].iloc[:,[0,1]], pre_post['Post1'].iloc[:,3:56]], axis=1),
                                                pd.concat([pre_post['Post2'].iloc[:,[0,1]], pre_post['Post2'].iloc[:,4:51]], axis=1)])}

subjective_measures_of_AC = pd.concat([pd.concat([pre_post['Post1'].iloc[:,[0,1]], pre_post['Post1'].iloc[:,56:82]], axis=1),
                             pd.concat([pre_post['Post2'].iloc[:,[0,1]], pre_post['Post2'].iloc[:,53:]], axis=1)])

In [62]:
initial = initial_raw.drop(columns=['Upload images of the session, if you have any', 'Other AD Services',
                               'External Resources', 'Unnamed: 18', 'Referrals [Academics]',
                               'STAFF Mentor', 'FACULTY Mentor','Referrals [Wellness]','Referrals [Health]', 
                                'Referrals'])
initial = initial.rename(columns={'Year in School:' : 'Year', 'Student Andrew ID' : 'AndrewID'})
initial = pd.merge(initial, students_complete, on='AndrewID')
len(initial)

148

In [77]:
L1 = list(subjective_measures_of_AC.iloc[:,2])
for i in range(len(L1)):
    name = L1[i]
    if not (name.strip() in list(ac_roster_full['Full Name']) or name.strip() in list(ac_roster_full['First Name'])
           or name.strip() in list(ac_roster_full['Pref Name'])):
        print(i,name)
L1[0] = 'Josh LeFevre'
L1[27] = 'Andrew Lee'
L1[53] = 'Clare Lai'
L1[67] = 'Michael Poljak'
L1[69] = 'Michael Poljak'
L1[84] = 'Melinda Looney'
L1[95] = 'Courtney Allred'
L1[99] = 'Young Do Kim'
L1[100] = 'Augustus Saalfeld'
L1[103] = 'Cristina'
L1[111] = 'Andrew Lee'
L1[117] = 'Michael Poljak'
L1[120] = 'Andrew Lee'
L1[135] = 'Michael Poljak'
L1[145] = 'Katie Lee'
L1[146] = 'Ziyi Xu'

for i in range(len(L1)):
    name = L1[i].strip()
    for index,row in ac_roster_full.iterrows():
        if(name == row['Full Name'] or name == row['First Name'] or name == row['Pref Name']):
            L1[i] = row['AndrewID']
            
subjective_measures_of_AC['AC'] = L1

0 Joshua Lefevre
27 Andrew (Siheon Lee)
53 Claire
67 Mike the best
69 Mike Poljak
84 Melinda L.
95 Coco Allred
99 steve (young do kim)
100 Augustus saalfield
103 Christina
111 Siheon Lee, Steve Kim
117 Michael Poljack
120 Siheon (Andrew)
135 Michael J Poljak
145 katie lee
146 Ziyi Xu (John Xu)

Current Dataframes:
- ac_roster_full (all AC info)
- pre_post dictionary for pre and post tests in 2018 and 2019 (4 dataframes) - raw
- students_complete (all students that have both pre and post test info)
- subjective_measures_of_self (subjective measures of student)
- subjective_measures_of_AC (subjective measures of AC/feedback)
- goals
- demographics
- initial (initial consultation info)

In [78]:
ac_roster_full.to_csv("Dataframes/ac_roster.csv")

pre_post['Pre1'].to_csv("Dataframes/RAW/pre18.csv")
pre_post['Post1'].to_csv("Dataframes/RAW/post18.csv")
pre_post['Pre2'].to_csv("Dataframes/RAW/pre19.csv")
pre_post['Post2'].to_csv("Dataframes/RAW/post19.csv")

subjective_measures_of_self['Pre'].to_csv("Dataframes/subjective_measures_of_self_pre.csv")
subjective_measures_of_self['Post'].to_csv("Dataframes/subjective_measures_of_self_post.csv")

subjective_measures_of_AC.to_csv("Dataframes/subjective_measures_of_AC.csv")
goals_pre.to_csv("Dataframes/goals_pre.csv")
goals_post.to_csv("Dataframes/goals_post.csv")
demographics.to_csv("Dataframes/demographics.csv")

initial.to_csv("Dataframes/initial.csv")